version: '3.9'
services:

  server:
    container_name: server
    build: server/ 
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - server:/usr/src/app
    environment:
            - PORT=3000
            - DB_HOST=db
            - DB_PORT=5432
            - DB_USERNAME=postgres
            - DB_PASSWORD=birmingham
            - DB_DATABASE=chatroom
            - JWT_SECRET='wAuv539rJReFsJfSusVsptWeb3xBTnMpXTt99PNHVcYnFGtU9TL8L9Cgmxr5En6r'
    networks:
            - database

  db:
    image: postgres
    container_name: postgresql
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: birmingham
      POSTGRES_USER: postgres
      POSTGRES_DB: chatroom
    networks:
      - database
      - dbpg4
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME:-chatroom}", "-U", "${DB_USER:-postgres}" ]
      interval: 1s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5432"

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5000
    networks:
      - dbpg4
    depends_on:
      - db
    ports:
      - "5050:5000"
    volumes:
      - pgadmin4-data:/var/lib/pgadmin

volumes:
  server:
  pgdata:
  pgadmin4-data:

networks:
  database:
  dbpg4: